### ISSUE TITLE
Feedback onderzoekvragen 

### ISSUE THREAD

**Issue by tilltheant** [SjorsWijsman/functional-programming#1]
Hee Sjors,

Interessante onderzoekvragen denk dat hier wel verrassende uitkomsten uit komen.

1. Welke aannames kan je maken aan de hand van de kleur van de auto?
Misschien heeft budget ook een grote invloed op welke kleur auto naast het soort baan?

2. Welke verbindingen zijn er tussen criminaliteit en de auto's die daarbij worden aangehouden? 
Misschien ook wel belangrijk wat voor soort criminaliteit niveau (BV: Drugs vervoer vs wapenbezit?) en dan het soort auto's per categorie van het niveau criminaliteit.

Hopelijk heb je wat aan mijn feedback.

Gr Anthony

**Comment by SjorsWijsman** [comment]
Thanks voor je feedback!
